language: python

python:
 - 2.7
 - 3.4
 - 3.5

env:
 - DJANGO=1.8
 - DJANGO=1.10
 - DJANGO=1.11

matrix:
  include:
    - python: 3.5
      env: TOXENV=flake8
    - python: 3.5
      env: DJANGO=master
    - python: 3.6
      env: DJANGO=master
  allow_failures:
    - env: DJANGO=master

install: pip install tox-travis codecov
script: tox
after_success: codecov
